spring:
  datasource:
    url: jdbc:mysql://localhost:3306/128?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 162434
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8088
springfox:
  swagger2:
    enabled: true

